# Generated by Django 6.0.5 on 2026-05-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
